FROM quay.io/pires/docker-elasticsearch-kubernetes:2.4.1
MAINTAINER Steve Sloka <slokas@upmc.edu>

# Builds: upmcenterprises/docker-elasticsearch-kubernetes:2.4.1

# Install kopf (https://github.com/lmenezes/elasticsearch-kopf)
RUN ./elasticsearch/bin/plugin install lmenezes/elasticsearch-kopf
